services:
  schrodinger-portal:
    image: ghcr.io/uncat2310/schrodinger-portal:latest
    build: .
    container_name: schrodinger-portal
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
